version: 2

submodules:
  include: all
  recursive: true

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"

sphinx:
  configuration: docs/source/conf.py

formats: all

python:
  install:
    - method: pip
      path: .
      extra_requirements:
          - docs
